### ISSUE TITLE
Unable to find weights for custom5 yolo and door yolo

### ISSUE THREAD

**Issue by pranay731** [verlab/robotSemanticMapping#1]
The links provided are not providing anything to download.
Also how can I isolate the run  of placing doors on map, where I already have a map? Can you please provide a more elaborate description on nodes and their publisher subscriber only for object placement on maps.

**Comment by renatojmsdh** [comment]
The server was temporarily down. The links should work now ;)
In case you have already a map...check the "localization-only" description and file example using AMCL mode.

**Comment by pranay731** [comment]
Hi,
I have been trying to download, the servers are up, but the link isn't valid. It yields a "404 not found error". Is there another link or something?
Thanks

**Comment by pranay731** [comment]
Hi,
Thanks for fixing the servers back.
